name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Lint and Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      plugin-id: ${{ steps.metadata.outputs.plugin-id }}
      plugin-version: ${{ steps.metadata.outputs.plugin-version }}
      has-backend: ${{ steps.check-for-backend.outputs.has-backend }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check Types
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test:ci

      - name: Build Frontend
        run: npm run build

      - name: Check for Backend
        id: check-for-backend
        run: |
          if [ -f "Magefile.go" ]
          then
            echo "has-backend=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Go
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Lint Backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: golangci/golangci-lint-action@v9

      - name: Test Backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v4
        with:
          version: latest
          args: coverage

      - name: Build Backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v4
        with:
          version: latest
          args: buildAll

      - name: Sign Plugin
        if: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN != '' }}
        run: npm run sign

      - name: Get Plugin Metadata
        id: metadata
        run: |
          sudo apt-get install jq

          export GRAFANA_PLUGIN_ID=$(cat dist/plugin.json | jq -r .id)
          export GRAFANA_PLUGIN_VERSION=$(cat dist/plugin.json | jq -r .info.version)
          export GRAFANA_PLUGIN_ARTIFACT=${GRAFANA_PLUGIN_ID}-${GRAFANA_PLUGIN_VERSION}.zip

          echo "plugin-id=${GRAFANA_PLUGIN_ID}" >> $GITHUB_OUTPUT
          echo "plugin-version=${GRAFANA_PLUGIN_VERSION}" >> $GITHUB_OUTPUT
          echo "archive=${GRAFANA_PLUGIN_ARTIFACT}" >> $GITHUB_OUTPUT

      - name: Package Plugin
        id: package-plugin
        run: |
          mv dist ${PLUGIN_ID}
          zip ${ARCHIVE} ${PLUGIN_ID} -r
        env:
          ARCHIVE: ${{ steps.metadata.outputs.archive }}
          PLUGIN_ID: ${{ steps.metadata.outputs.plugin-id }}

      - name: Check "plugin.json"
        run: |
          docker run --pull=always \
            -v $PWD/${ARCHIVE}:/archive.zip \
            grafana/plugin-validator-cli -analyzer=metadatavalid /archive.zip
        env:
          ARCHIVE: ${{ steps.metadata.outputs.archive }}

      - name: Archive Build
        uses: actions/upload-artifact@v7
        with:
          name:
            ${{ steps.metadata.outputs.plugin-id }}-${{
            steps.metadata.outputs.plugin-version }}
          path: ${{ steps.metadata.outputs.plugin-id }}
          retention-days: 5
